version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - /Users/sonarone/java/deploy/root/nginx/html:/usr/share/nginx/html
    - /Users/sonarone/java/deploy/root/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
  mysql:
    image: mysql:5.7.27
    ports:
    - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis:latest
  vueblog:
    image: vueblog:latest
    build: .
    ports:
    - 8081:8081
    depends_on:
      - mysql
      - redis